### ISSUE TITLE
User Defined Souffle functions in Haskell

### ISSUE THREAD

**Issue by samirsa-csco** [luc-tielen/souffle-haskell#3]
This is a great project. 
Do you think you could guide on an idiomatic way to link a Haskell implementation of User Defined Souffle functions. For e.g. in the given example, can "Reachable" be implemented in Haskell. 

There are some constraints how Soufflé's supports such functions - https://souffle-lang.github.io/functors, but I think that such an implementation can be provided with C calling back into Haskell.

thanks.

**Comment by luc-tielen** [comment]
Hi,

First of all, thanks for the suggestion! However I have been really sick the past few weeks so I need to rest a lot and can only go on my computer for short amounts of time, so I'm afraid I currently can't guide you :sweat_smile:..

To answer the rest of your question: I think it would be quite hard to implement a predicate like `Reachable` in Haskell, and would most likely require a lot of template Haskell (and potentially a lot more type level information). This is something I would rather avoid, since it makes using this library more obscure. Also you would have to call the souffle compiler correctly at compile time and then use `embedProgram` to embed the generated code.

Also if you want to add functors to Souffle it would require dynamic linking with another C-library (that would have to be generated from Haskell code somehow). I initially tried dynamic linking for the generated C++ code by Souffle but this gave problems due to the way the generated code works, so I foresee a lot more problems there as well. (And I have no idea how to deal with the multithreading safety in Souffle).

The way the library is currently setup is as follows: Souffle exposes a C++ interface. I wrote a small C-compatible layer around it that Haskell can call. Then I wrote some more functions on top of the low level bindings to achieve a higher-level DSL that is fairly hard to use in a wrong way. 

Hope this information helps :smiley:.

**Comment by luc-tielen** [comment]
I'm closing this issue, due to the very big complexity involved in this feature request (really hard to interface with souffle), while offering not that much value in return.. (and I don't find the datalog code to be bad/difficult to write).
