### ISSUE TITLE
Many warnings with GHC 8.10.2

### ISSUE THREAD

**Issue by sordina** [luc-tielen/souffle-haskell#34]
Adding `-Wno-prepositive-qualified-module -Wno-missing-safe-haskell-mode` to the GHC options eliminates a lot of warnings that don't seem very useful.

Adding `{-# LANGUAGE TypeFamilyDependencies #-}` to `lib/Language/Souffle/Experimental.hs` fixes an error.

**Comment by luc-tielen** [comment]
Hi, thank you for reporting this!

Due to real life things, I'm a little behind on the maintenance work 😅. I've tried adding support for GHC8.10 in the past but I ran into issues with getting the Nix setup properly up and running.

The warnings don't seem too bad, the error surprises me though.
Could you make a pull request with these changes?

Thanks!

**Comment by sordina** [comment]
Sure thing!

**Comment by sordina** [comment]
https://github.com/luc-tielen/souffle-haskell/pull/35

**Comment by luc-tielen** [comment]
Merged in #35.
